name: Build and Deploy (CI/CD)

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    name: Build and Deploy (CI/CD)
    runs-on: ubuntu-latest
    env:
      node-version: '16.17.0'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - run: yarn install --frozen-lockfile
      - run: mkdir public/images/nextImageExportOptimizer
      - run: yarn export

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             us-east-1

      - name: Deploy to S3
        run: aws s3 sync ./out/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Deploy to CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*' 